# Generated by Django 5.0.6 on 2024-06-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
