# Generated by Django 5.0.6 on 2024-06-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_posts_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='video',
        ),
    ]
